import { z } from 'zod'

// Mirrors the trade snapshot the MT-Dashboard worker puts in the
// repository_dispatch client_payload. klines are Binance candles over the
// trade window ([openTime, open, high, low, close]) fetched worker-side;
// without them build-props fails the render (playout is candle-only).
export const tradeSchema = z.object({
  trade_id: z.string(),
  bot_name: z.string(),
  symbol: z.string(),
  side: z.string(),
  filled_at: z.string().nullish(),
  entry: z.number().nullish(),
  close: z.number().nullish(),
  reason: z.string().nullish(),
  closed_at: z.string().nullish(),
  pnl_pct: z.number().nullish(),
  pnl_r: z.number().nullish(),
  leverage: z.number().nullish(),
  take_profit: z.number().nullish(),
  initial_stop: z.number().nullish(),
  // minutes east of UTC for the naive dashboard-local timestamps above
  tz_offset_minutes: z.number().nullish(),
  klines: z.array(z.tuple([z.number(), z.number(), z.number(), z.number(), z.number()])).nullish(),
})

// Generated by scripts/voiceover.mjs before the render: the narration track
// plus its measured length (the playout composition stretches its candle
// pacing to fit), and the optional ducked music bed.
export const voiceoverSchema = z.object({
  src: z.string(),
  durationSeconds: z.number(),
  voice: z.string(),
  script: z.string(),
  source: z.string(),
})

export const musicSchema = z.object({
  src: z.string(),
  volume: z.number(),
})

export const alertSchema = z.object({
  src: z.string(),
  volume: z.number(),
})

export const videoPropsSchema = z.object({
  trade: tradeSchema,
  voiceover: voiceoverSchema.nullish(),
  music: musicSchema.nullish(),
  alert: alertSchema.nullish(),
  // per-section style overrides; unset sections pick their family
  // deterministically from the trade id at render time (families listed in
  // templates/styles.tsx: chart candle|bar, intro oneline|stacked|classic|
  // bigside, result duo|stacked|classic|heror)
  styles: z
    .object({
      chart: z.string().nullish(),
      intro: z.string().nullish(),
      result: z.string().nullish(),
    })
    .nullish(),
})

export type VideoProps = z.infer<typeof videoPropsSchema>
export type Voiceover = z.infer<typeof voiceoverSchema>
export type Music = z.infer<typeof musicSchema>
export type Alert = z.infer<typeof alertSchema>
export type Trade = z.infer<typeof tradeSchema>
